# Build and test CPAN module: ParserLR

name: Test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: |
        sudo apt update
        sudo apt -y install build-essential tree
        sudo cpan install Data::DFA Data::NFA Data::Table::Text

    - name: Test
      run: |
        tree
        perl Build.PL
        perl Build test
